import { SKINS } from "./skins" // Assuming SKINS is declared in another file

export const COMBAT_ITEMS = [
  {
    id: "super_laser",
    name: { en: "Super Laser", vi: "Laser Siêu Mạnh" },
    description: { en: "Piercing laser that goes through all enemies", vi: "Tia laser xuyên qua mọi kẻ địch" },
    emoji: "🔫",
    color: "#ef4444",
    duration: 10000,
    cooldown: 30000,
    effect: "piercing_shot",
    rarity: "epic",
    cost: 200,
    hotkey: "R",
  },
  {
    id: "energy_shield",
    name: { en: "Energy Shield", vi: "Khiên Năng Lượng" },
    description: { en: "Absorbs one hit from any source", vi: "Hấp thụ một đòn tấn công bất kỳ" },
    emoji: "🛡️",
    color: "#06b6d4",
    duration: 0, // Instant use
    cooldown: 45000,
    effect: "one_hit_shield",
    rarity: "rare",
    cost: 150,
    hotkey: "T",
  },
  {
    id: "time_dilation",
    name: { en: "Time Dilation", vi: "Slow Motion" },
    description: { en: "Slows down enemies and projectiles", vi: "Làm chậm kẻ địch và đạn bắn" },
    emoji: "⏰",
    color: "#8b5cf6",
    duration: 3000,
    cooldown: 60000,
    effect: "slow_motion",
    rarity: "epic",
    cost: 250,
    hotkey: "R",
  },
  {
    id: "invincibility",
    name: { en: "Invincibility", vi: "Bất Tử" },
    description: { en: "Complete immunity to all damage", vi: "Miễn nhiễm hoàn toàn với mọi sát thương" },
    emoji: "✨",
    color: "#fbbf24",
    duration: 5000,
    cooldown: 90000,
    effect: "invincible",
    rarity: "legendary",
    cost: 400,
    hotkey: "T",
  },
  {
    id: "speed_boost",
    name: { en: "Speed Boost", vi: "Tăng Tốc" },
    description: { en: "Increases movement speed dramatically", vi: "Tăng tốc độ di chuyển đáng kể" },
    emoji: "💨",
    color: "#22c55e",
    duration: 3000,
    cooldown: 40000,
    effect: "speed_boost",
    rarity: "rare",
    cost: 180,
    hotkey: "R",
  },
  {
    id: "boomerang_shot",
    name: { en: "Boomerang Shot", vi: "Đạn Boomerang" },
    description: { en: "Bullets return after hitting targets", vi: "Đạn quay lại sau khi trúng mục tiêu" },
    emoji: "🪃",
    color: "#f59e0b",
    duration: 8000,
    cooldown: 35000,
    effect: "boomerang_bullets",
    rarity: "epic",
    cost: 220,
    hotkey: "T",
  },
  {
    id: "ghost_phase",
    name: { en: "Ghost Phase", vi: "Pha Ma" },
    description: { en: "Pass through objects but cannot shoot", vi: "Đi xuyên vật thể nhưng không thể bắn" },
    emoji: "👻",
    color: "#a855f7",
    duration: 3000,
    cooldown: 50000,
    effect: "ghost_mode",
    rarity: "epic",
    cost: 280,
    hotkey: "R",
  },
  {
    id: "time_freeze",
    name: { en: "Time Crystal", vi: "Tinh Thể Thời Gian" },
    description: { en: "Freezes all enemies for 2 seconds", vi: "Đóng băng tất cả kẻ địch trong 2 giây" },
    emoji: "💎",
    color: "#06b6d4",
    duration: 2000,
    cooldown: 120000,
    effect: "time_freeze",
    rarity: "legendary",
    cost: 500,
    hotkey: "T",
  },
  {
    id: "shadow_clone",
    name: { en: "Shadow Clone", vi: "Bóng Ma" },
    description: { en: "Creates a shadow that follows and shoots", vi: "Tạo bóng ma theo sau và bắn phụ" },
    emoji: "🌑",
    color: "#374151",
    duration: 5000,
    cooldown: 70000,
    effect: "shadow_clone",
    rarity: "legendary",
    cost: 350,
    hotkey: "R",
  },
]

export const ENHANCED_SKINS = [
  ...SKINS, // Keep existing skins
  {
    id: "golden_chicken",
    name: { en: "Golden Chicken", vi: "Gà Vàng" },
    description: { en: "Legendary golden chicken with luck boost", vi: "Gà vàng huyền thoại tăng may mắn" },
    emoji: "🐓",
    color: "#fbbf24",
    cost: 300,
    rarity: "legendary",
    specialEffect: "luck_boost",
  },
  {
    id: "angel_chicken",
    name: { en: "Angel Chicken", vi: "Gà Thiên Thần" },
    description: { en: "Divine chicken with healing aura", vi: "Gà thiên thần với hào quang chữa lành" },
    emoji: "👼",
    color: "#f3f4f6",
    cost: 400,
    rarity: "legendary",
    specialEffect: "healing_aura",
  },
  {
    id: "robot_chicken",
    name: { en: "Cyber Chicken", vi: "Gà Robot" },
    description: { en: "Mechanical chicken with tech upgrades", vi: "Gà máy với nâng cấp công nghệ" },
    emoji: "🤖",
    color: "#6b7280",
    cost: 250,
    rarity: "epic",
    specialEffect: "tech_boost",
  },
  {
    id: "punk_chicken",
    name: { en: "Punk Chicken", vi: "Gà Punk" },
    description: { en: "Rebellious chicken with attitude", vi: "Gà nổi loạn với thái độ" },
    emoji: "🎸",
    color: "#ef4444",
    cost: 200,
    rarity: "epic",
    specialEffect: "damage_boost",
  },
  {
    id: "pixel_chicken",
    name: { en: "Retro Pixel Chicken", vi: "Gà Pixel Retro" },
    description: { en: "8-bit nostalgic chicken", vi: "Gà 8-bit hoài cổ" },
    emoji: "🕹️",
    color: "#22c55e",
    cost: 180,
    rarity: "rare",
    specialEffect: "retro_mode",
  },
  {
    id: "space_chicken",
    name: { en: "Cosmic Chicken", vi: "Gà Không Gian" },
    description: { en: "Intergalactic chicken explorer", vi: "Gà khám phá liên thiên hà" },
    emoji: "🚀",
    color: "#8b5cf6",
    cost: 350,
    rarity: "legendary",
    specialEffect: "cosmic_power",
  },
]
