export const SKINS = [
  {
    id: "default",
    name: { en: "Classic Ship", vi: "Tàu Cổ Điển" },
    description: { en: "The original spacecraft", vi: "Tàu vũ trụ nguyên bản" },
    emoji: "🚀",
    color: "#3b82f6",
    cost: 0,
  },
  {
    id: "fire",
    name: { en: "Fire Phoenix", vi: "Phượng Hoàng Lửa" },
    description: { en: "Blazing hot phoenix", vi: "Phượng hoàng rực lửa" },
    emoji: "🔥",
    color: "#ef4444",
    cost: 50,
  },
  {
    id: "ice",
    name: { en: "Ice Crystal", vi: "Tinh Thể Băng" },
    description: { en: "Frozen crystal ship", vi: "Tàu tinh thể băng giá" },
    emoji: "❄️",
    color: "#06b6d4",
    cost: 75,
  },
  {
    id: "lightning",
    name: { en: "Thunder Bolt", vi: "Tia Sét" },
    description: { en: "Electric powered ship", vi: "Tàu chạy bằng điện" },
    emoji: "⚡",
    color: "#eab308",
    cost: 100,
  },
  {
    id: "rainbow",
    name: { en: "Rainbow Dash", vi: "Cầu Vồng" },
    description: { en: "Colorful rainbow ship", vi: "Tàu cầu vồng đầy màu sắc" },
    emoji: "🌈",
    color: "#a855f7",
    cost: 150,
  },
  {
    id: "alien",
    name: { en: "UFO Saucer", vi: "Đĩa Bay UFO" },
    description: { en: "Mysterious alien craft", vi: "Tàu người ngoài hành tinh bí ẩn" },
    emoji: "🛸",
    color: "#10b981",
    cost: 200,
  },
  {
    id: "dragon",
    name: { en: "Dragon Wing", vi: "Cánh Rồng" },
    description: { en: "Mythical dragon ship", vi: "Tàu rồng huyền thoại" },
    emoji: "🐉",
    color: "#dc2626",
    cost: 250,
  },
  {
    id: "star",
    name: { en: "Shooting Star", vi: "Sao Băng" },
    description: { en: "Bright shooting star", vi: "Sao băng sáng chói" },
    emoji: "⭐",
    color: "#f59e0b",
    cost: 300,
  },
]
