export const SKINS = [
  {
    id: "default",
    name: { en: "Classic Rocket", vi: "Tên Lửa Cổ Điển" },
    description: { en: "The original spacecraft for beginners", vi: "Tàu vũ trụ nguyên bản cho người mới" },
    emoji: "🚀",
    color: "#3b82f6",
    cost: 0,
    rarity: "common",
  },
  {
    id: "fire",
    name: { en: "Phoenix Blaze", vi: "Phượng Hoàng Lửa" },
    description: { en: "Blazing hot phoenix with fire trails", vi: "Phượng hoàng rực lửa với đuôi lửa" },
    emoji: "🔥",
    color: "#ef4444",
    cost: 50,
    rarity: "rare",
  },
  {
    id: "ice",
    name: { en: "Frost Crystal", vi: "Tinh Thể Băng" },
    description: { en: "Frozen crystal ship with ice powers", vi: "Tàu tinh thể băng với sức mạnh băng giá" },
    emoji: "❄️",
    color: "#06b6d4",
    cost: 75,
    rarity: "rare",
  },
  {
    id: "lightning",
    name: { en: "Thunder Strike", vi: "Sét Đánh" },
    description: { en: "Electric powered ship with lightning speed", vi: "Tàu chạy điện với tốc độ ánh sáng" },
    emoji: "⚡",
    color: "#eab308",
    cost: 100,
    rarity: "epic",
  },
  {
    id: "rainbow",
    name: { en: "Cosmic Rainbow", vi: "Cầu Vồng Vũ Trụ" },
    description: {
      en: "Colorful rainbow ship with prismatic effects",
      vi: "Tàu cầu vồng đầy màu sắc với hiệu ứng lăng kính",
    },
    emoji: "🌈",
    color: "#a855f7",
    cost: 150,
    rarity: "epic",
  },
  {
    id: "alien",
    name: { en: "UFO Mothership", vi: "Tàu Mẹ UFO" },
    description: { en: "Advanced alien technology spacecraft", vi: "Tàu vũ trụ công nghệ người ngoài hành tinh" },
    emoji: "🛸",
    color: "#10b981",
    cost: 200,
    rarity: "epic",
  },
  {
    id: "dragon",
    name: { en: "Cosmic Dragon", vi: "Rồng Vũ Trụ" },
    description: { en: "Mythical dragon with cosmic powers", vi: "Rồng huyền thoại với sức mạnh vũ trụ" },
    emoji: "🐉",
    color: "#dc2626",
    cost: 300,
    rarity: "legendary",
  },
  {
    id: "star",
    name: { en: "Stellar Nova", vi: "Sao Băng Nova" },
    description: { en: "Bright shooting star with stellar energy", vi: "Sao băng sáng với năng lượng sao" },
    emoji: "⭐",
    color: "#f59e0b",
    cost: 250,
    rarity: "legendary",
  },
  {
    id: "galaxy",
    name: { en: "Galaxy Cruiser", vi: "Tàu Thiên Hà" },
    description: { en: "Harness the power of entire galaxies", vi: "Khai thác sức mạnh của cả thiên hà" },
    emoji: "🌌",
    color: "#8b5cf6",
    cost: 400,
    rarity: "legendary",
  },
  {
    id: "void",
    name: { en: "Void Walker", vi: "Kẻ Đi Trong Hư Vô" },
    description: { en: "Master of darkness and void energy", vi: "Chủ nhân của bóng tối và năng lượng hư vô" },
    emoji: "🕳️",
    color: "#1f2937",
    cost: 500,
    rarity: "legendary",
  },
]

export const TRAILS = [
  {
    id: "default",
    name: { en: "Basic Trail", vi: "Đuôi Cơ Bản" },
    description: { en: "Simple particle trail", vi: "Đuôi hạt đơn giản" },
    emoji: "✨",
    color: "#ffffff",
    cost: 0,
    rarity: "common",
  },
  {
    id: "fire_trail",
    name: { en: "Fire Trail", vi: "Đuôi Lửa" },
    description: { en: "Blazing fire particles", vi: "Hạt lửa rực cháy" },
    emoji: "🔥",
    color: "#ff4500",
    cost: 80,
    rarity: "rare",
  },
  {
    id: "ice_trail",
    name: { en: "Frost Trail", vi: "Đuôi Băng" },
    description: { en: "Frozen ice crystals", vi: "Tinh thể băng đông lạnh" },
    emoji: "❄️",
    color: "#00bfff",
    cost: 80,
    rarity: "rare",
  },
  {
    id: "rainbow_trail",
    name: { en: "Rainbow Trail", vi: "Đuôi Cầu Vồng" },
    description: { en: "Colorful rainbow particles", vi: "Hạt cầu vồng đầy màu sắc" },
    emoji: "🌈",
    color: "#ff69b4",
    cost: 120,
    rarity: "epic",
  },
  {
    id: "lightning_trail",
    name: { en: "Electric Trail", vi: "Đuôi Điện" },
    description: { en: "Crackling electricity", vi: "Điện tia chớp" },
    emoji: "⚡",
    color: "#ffff00",
    cost: 150,
    rarity: "epic",
  },
  {
    id: "galaxy_trail",
    name: { en: "Cosmic Trail", vi: "Đuôi Vũ Trụ" },
    description: { en: "Swirling galaxy particles", vi: "Hạt thiên hà xoáy tròn" },
    emoji: "🌌",
    color: "#9370db",
    cost: 200,
    rarity: "legendary",
  },
]

export const BACKGROUNDS = [
  {
    id: "default",
    name: { en: "Deep Space", vi: "Không Gian Sâu" },
    description: { en: "Classic starfield background", vi: "Nền sao cổ điển" },
    emoji: "🌌",
    color: "#1a1a2e",
    cost: 0,
    rarity: "common",
  },
  {
    id: "nebula",
    name: { en: "Cosmic Nebula", vi: "Tinh Vân Vũ Trụ" },
    description: { en: "Colorful space nebula", vi: "Tinh vân không gian đầy màu sắc" },
    emoji: "🌠",
    color: "#4a0e4e",
    cost: 100,
    rarity: "rare",
  },
  {
    id: "galaxy",
    name: { en: "Spiral Galaxy", vi: "Thiên Hà Xoắn Ốc" },
    description: { en: "Beautiful spiral galaxy view", vi: "Cảnh thiên hà xoắn ốc tuyệt đẹp" },
    emoji: "🌌",
    color: "#2d1b69",
    cost: 150,
    rarity: "epic",
  },
  {
    id: "blackhole",
    name: { en: "Black Hole", vi: "Hố Đen" },
    description: { en: "Mysterious black hole environment", vi: "Môi trường hố đen bí ẩn" },
    emoji: "🕳️",
    color: "#000000",
    cost: 200,
    rarity: "legendary",
  },
]

export const POWER_UPS = [
  {
    id: "shield_boost",
    name: { en: "Shield Booster", vi: "Tăng Cường Khiên" },
    description: { en: "Extends shield duration by 3 seconds", vi: "Tăng thời gian khiên thêm 3 giây" },
    emoji: "🛡️",
    color: "#00ffff",
    cost: 150,
    rarity: "rare",
  },
  {
    id: "fire_boost",
    name: { en: "Rapid Fire", vi: "Bắn Nhanh" },
    description: { en: "Increases fire rate by 50%", vi: "Tăng tốc độ bắn 50%" },
    emoji: "🔫",
    color: "#ff6b35",
    cost: 120,
    rarity: "rare",
  },
  {
    id: "score_multiplier",
    name: { en: "Score Multiplier", vi: "Nhân Điểm" },
    description: { en: "Double points for 30 seconds", vi: "Nhân đôi điểm trong 30 giây" },
    emoji: "💰",
    color: "#ffd700",
    cost: 200,
    rarity: "epic",
  },
  {
    id: "mega_bomb",
    name: { en: "Mega Bomb", vi: "Bom Khổng Lồ" },
    description: { en: "Destroys everything on screen", vi: "Phá hủy mọi thứ trên màn hình" },
    emoji: "💣",
    color: "#ff0000",
    cost: 300,
    rarity: "legendary",
  },
]
