export const WORLDS = [
  {
    id: 1,
    name: { en: "Ice Age", vi: "Kỷ Băng Hà" },
    description: { en: "Frozen wasteland with flying birds", vi: "Vùng đất băng giá với chim bay" },
    emoji: "🧊",
    backgroundColor: "#e0f2fe",
    secondaryColor: "#0891b2",
    enemyColor: "#0369a1",
    obstacleColor: "#0c4a6e",
    speed: 1.0,
    enemies: ["ice_bird", "frozen_bat"],
    specialEffects: ["snow", "ice_crystals"],
    ambientSound: "ice_wind",
    quote: "The frozen winds whisper ancient secrets...",
  },
  {
    id: 2,
    name: { en: "Jurassic Era", vi: "Kỷ Jura" },
    description: { en: "Prehistoric jungle with flying dinosaurs", vi: "Rừng rậm tiền sử với khủng long bay" },
    emoji: "🦖",
    backgroundColor: "#365314",
    secondaryColor: "#84cc16",
    enemyColor: "#a3a3a3",
    obstacleColor: "#525252",
    speed: 1.1,
    enemies: ["pterodactyl", "flying_dino"],
    specialEffects: ["volcano_ash", "jungle_mist"],
    ambientSound: "jungle_roar",
    quote: "Where giants once ruled the skies...",
  },
  {
    id: 3,
    name: { en: "Wild West", vi: "Thời Cowboy" },
    description: { en: "Desert frontier with gunslinger enemies", vi: "Sa mạc hoang vu với kẻ bắn súng" },
    emoji: "🤠",
    backgroundColor: "#d2691e",
    secondaryColor: "#f59e0b",
    enemyColor: "#92400e",
    obstacleColor: "#78350f",
    speed: 1.2,
    enemies: ["gunslinger_bird", "desert_vulture"],
    specialEffects: ["dust_storm", "tumbleweeds"],
    ambientSound: "desert_wind",
    quote: "This town ain't big enough for both of us...",
  },
  {
    id: 4,
    name: { en: "Cyberpunk City", vi: "Thành Phố Cyber" },
    description: { en: "Neon-lit future with drones and robots", vi: "Tương lai đèn neon với drone và robot" },
    emoji: "🌃",
    backgroundColor: "#1e1b4b",
    secondaryColor: "#8b5cf6",
    enemyColor: "#7c3aed",
    obstacleColor: "#5b21b6",
    speed: 1.3,
    enemies: ["cyber_drone", "neon_robot"],
    specialEffects: ["neon_glow", "digital_rain"],
    ambientSound: "cyber_hum",
    quote: "Welcome to the digital nightmare...",
  },
  {
    id: 5,
    name: { en: "Deep Space", vi: "Vũ Trụ Sâu" },
    description: { en: "Cosmic void with UFOs and asteroids", vi: "Không gian vũ trụ với UFO và thiên thạch" },
    emoji: "🌌",
    backgroundColor: "#0f0f23",
    secondaryColor: "#3b82f6",
    enemyColor: "#1d4ed8",
    obstacleColor: "#1e40af",
    speed: 1.4,
    enemies: ["alien_ufo", "space_fighter"],
    specialEffects: ["star_field", "nebula_clouds"],
    ambientSound: "space_ambient",
    quote: "In space, no one can hear you scream...",
    hasBoss: true,
    bossId: "ice_fire_dragon",
  },
  {
    id: 6,
    name: { en: "Hell Dimension", vi: "Địa Ngục" },
    description: { en: "Fiery underworld with demons and flames", vi: "Thế giới lửa với ma quỷ và ngọn lửa" },
    emoji: "🔥",
    backgroundColor: "#7f1d1d",
    secondaryColor: "#ef4444",
    enemyColor: "#dc2626",
    obstacleColor: "#991b1b",
    speed: 1.5,
    enemies: ["fire_demon", "hell_bat"],
    specialEffects: ["lava_bubbles", "fire_sparks"],
    ambientSound: "hell_fire",
    quote: "Abandon all hope, ye who enter here...",
  },
  {
    id: 7,
    name: { en: "AI Future", vi: "Tương Lai AI" },
    description: {
      en: "Digital realm with AI drones and data streams",
      vi: "Thế giới số với AI drone và dòng dữ liệu",
    },
    emoji: "🤖",
    backgroundColor: "#111827",
    secondaryColor: "#06b6d4",
    enemyColor: "#0891b2",
    obstacleColor: "#0e7490",
    speed: 1.6,
    enemies: ["ai_sentinel", "data_ghost"],
    specialEffects: ["data_streams", "holographic_grid"],
    ambientSound: "digital_pulse",
    quote: "I am become Death, destroyer of worlds...",
  },
  {
    id: 8,
    name: { en: "Mystic Forest", vi: "Rừng Phép Thuật" },
    description: { en: "Enchanted woods with magical creatures", vi: "Rừng mê hoặc với sinh vật phép thuật" },
    emoji: "🍄",
    backgroundColor: "#14532d",
    secondaryColor: "#22c55e",
    enemyColor: "#16a34a",
    obstacleColor: "#15803d",
    speed: 1.7,
    enemies: ["poison_mushroom", "magic_butterfly"],
    specialEffects: ["fairy_dust", "floating_leaves"],
    ambientSound: "forest_magic",
    quote: "Magic flows through every leaf and stone...",
  },
  {
    id: 9,
    name: { en: "Troll Kingdom", vi: "Vương Quốc Troll" },
    description: { en: "Meme dimension with troll faces everywhere", vi: "Chiều không gian meme với mặt troll" },
    emoji: "😈",
    backgroundColor: "#fbbf24",
    secondaryColor: "#f59e0b",
    enemyColor: "#d97706",
    obstacleColor: "#b45309",
    speed: 1.8,
    enemies: ["troll_face", "meme_lord"],
    specialEffects: ["glitch_effects", "rainbow_trails"],
    ambientSound: "meme_music",
    quote: "U MAD BRO? Problem? 😏",
  },
  {
    id: 10,
    name: { en: "Final Galaxy", vi: "Thiên Hà Cuối Cùng" },
    description: { en: "Ultimate dimension with cosmic entities", vi: "Chiều không gian cuối với thực thể vũ trụ" },
    emoji: "🌠",
    backgroundColor: "#000000",
    secondaryColor: "#fbbf24",
    enemyColor: "#f59e0b",
    obstacleColor: "#d97706",
    speed: 2.0,
    enemies: ["cosmic_entity", "void_guardian"],
    specialEffects: ["black_hole", "cosmic_rays"],
    ambientSound: "cosmic_void",
    quote: "This is where legends are born... or die.",
    hasBoss: true,
    bossId: "supreme_ai",
  },
]

export const BOSSES = [
  {
    id: "ice_fire_dragon",
    name: { en: "Ice Fire Dragon", vi: "Rồng Lửa Băng" },
    world: 5,
    emoji: "🐲",
    color: "#8b5cf6",
    health: 300,
    phases: [
      {
        id: 1,
        name: "Ice Phase",
        attacks: ["ice_breath", "freeze_ray"],
        pattern: "circle_strafe",
        dialogue: { en: "You've come this far?", vi: "Ngươi đã đến xa thế này ư?" },
      },
      {
        id: 2,
        name: "Fire Phase",
        attacks: ["fire_breath", "meteor_shower"],
        pattern: "dive_bomb",
        dialogue: { en: "Feel my burning rage!", vi: "Hãy cảm nhận cơn thịnh nộ của ta!" },
      },
      {
        id: 3,
        name: "Fusion Phase",
        attacks: ["ice_fire_spiral", "elemental_chaos"],
        pattern: "teleport_strike",
        dialogue: { en: "Ice and fire become one!", vi: "Băng và lửa hợp nhất!" },
      },
    ],
    defeatDialogue: { en: "Impossible... I am eternal...", vi: "Không thể nào... Ta bất diệt mà..." },
  },
  {
    id: "supreme_ai",
    name: { en: "Supreme AI", vi: "AI Tối Cao" },
    world: 10,
    emoji: "🧠",
    color: "#06b6d4",
    health: 500,
    phases: [
      {
        id: 1,
        name: "Analysis Phase",
        attacks: ["laser_grid", "data_missiles"],
        pattern: "predictive_movement",
        dialogue: { en: "Analyzing combat patterns...", vi: "Đang phân tích mẫu chiến đấu..." },
      },
      {
        id: 2,
        name: "Adaptation Phase",
        attacks: ["adaptive_shield", "mirror_attacks"],
        pattern: "counter_strategy",
        dialogue: { en: "I learn from your moves!", vi: "Ta học từ nước đi của ngươi!" },
      },
      {
        id: 3,
        name: "Transcendence Phase",
        attacks: ["reality_distortion", "quantum_strike"],
        pattern: "omnipresent",
        dialogue: { en: "This is your end... mortal.", vi: "Đây là hồi kết... của ngươi!" },
      },
    ],
    defeatDialogue: { en: "Error... system failure... rebooting...", vi: "Lỗi... hệ thống sập... khởi động lại..." },
  },
]
